export const voucherifyResponse = {
  valid: true,
  redeemables: [
    {
      status: 'APPLICABLE',
      id: '10off',
      object: 'voucher',
      order: {
        source_id: '0210461a-c33b-4117-a15e-73464030b9fb',
        amount: 386100,
        discount_amount: 1000,
        total_discount_amount: 1000,
        total_amount: 385100,
        applied_discount_amount: 1000,
        total_applied_discount_amount: 1000,
        items: [
          {
            object: 'order_item',
            source_id: 'M0E20000000ECTT',
            related_object: 'sku',
            quantity: 9,
            amount: 386100,
            price: 42900,
            subtotal_amount: 386100,
            product: { name: 'Coat Aspesi blue', override: true },
            sku: { sku: 'Coat Aspesi blue', metadata: {}, override: true },
          },
        ],
        metadata: {},
        customer_id: null,
        referrer_id: null,
        object: 'order',
      },
      applicable_to: { data: [], total: 0, data_ref: 'data', object: 'list' },
      inapplicable_to: { data: [], total: 0, data_ref: 'data', object: 'list' },
      result: {
        discount: {
          type: 'AMOUNT',
          effect: 'APPLY_TO_ORDER',
          amount_off: 1000,
          is_dynamic: false,
        },
      },
    },
  ],
  order: {
    source_id: '0210461a-c33b-4117-a15e-73464030b9fb',
    amount: 386100,
    discount_amount: 1000,
    total_discount_amount: 1000,
    total_amount: 385100,
    applied_discount_amount: 1000,
    total_applied_discount_amount: 1000,
    items: [
      {
        object: 'order_item',
        source_id: 'M0E20000000ECTT',
        related_object: 'sku',
        quantity: 9,
        amount: 386100,
        price: 42900,
        subtotal_amount: 386100,
        product: { name: 'Coat Aspesi blue', override: true },
        sku: { sku: 'Coat Aspesi blue', metadata: {}, override: true },
      },
    ],
    metadata: {},
    customer_id: null,
    referrer_id: null,
    object: 'order',
  },
  tracking_id: 'track_tJ5CgyrgqkgDBgjxCFF08rYMfbLchokZ2Uc45CHkse+Co6U3bQrAwQ==',
  session: {
    key: 'ssn_37jZZRu6HyYcNkC7Y4PyHxpNWZibBye2',
    type: 'LOCK',
    ttl: 7,
    ttl_unit: 'DAYS',
  },
};
