export const dataToRunCartActionsBuilder = {
  availablePromotions: [],
  applicableCoupons: [
    {
      status: 'APPLICABLE',
      id: '10off',
      object: 'voucher',
      order: {
        source_id: 'fd399771-99ee-4a69-9b87-560f76816a2f',
        amount: 92875,
        discount_amount: 1000,
        total_discount_amount: 1000,
        total_amount: 91875,
        applied_discount_amount: 1000,
        total_applied_discount_amount: 1000,
        items: [
          {
            object: 'order_item',
            source_id: 'M0E20000000EE54',
            related_object: 'sku',
            quantity: 1,
            amount: 18500,
            price: 18500,
            subtotal_amount: 18500,
            product: { name: 'Jeans Cycle dark blue', override: true },
            sku: { sku: 'Jeans Cycle dark blue', metadata: {}, override: true },
          },
          {
            object: 'order_item',
            source_id: 'M0E20000000EE54',
            related_object: 'sku',
            quantity: 2,
            amount: 37000,
            price: 18500,
            subtotal_amount: 37000,
            product: { name: 'Jeans Cycle dark blue', override: true },
            sku: { sku: 'Jeans Cycle dark blue', metadata: {}, override: true },
          },
          {
            object: 'order_item',
            source_id: 'M0E20000000ELDI',
            related_object: 'sku',
            product_id: 'prod_0d1abfb839c51910d8',
            quantity: 1,
            amount: 37375,
            price: 37375,
            subtotal_amount: 37375,
            product: {
              id: 'prod_0d1abfb839c51910d8',
              source_id: '253ec97b-f8ac-4a14-94e2-150f5ab0510a',
              name: 'Casual jacket Michael Kors beige',
              override: true,
            },
            sku: {
              id: 'sku_0d1ac1959a4c544f3b',
              source_id: 'M0E20000000ELDI',
              sku: 'Casual jacket Michael Kors beige',
              metadata: {},
              price: 37375,
              override: true,
            },
          },
        ],
        metadata: {},
        customer_id: null,
        referrer_id: null,
        object: 'order',
      },
      applicable_to: { data: [], total: 0, data_ref: 'data', object: 'list' },
      inapplicable_to: { data: [], total: 0, data_ref: 'data', object: 'list' },
      result: {
        discount: {
          type: 'AMOUNT',
          effect: 'APPLY_TO_ORDER',
          amount_off: 1000,
          is_dynamic: false,
        },
      },
    },
    {
      status: 'APPLICABLE',
      id: '10OFFITEM',
      object: 'voucher',
      order: {
        source_id: 'fd399771-99ee-4a69-9b87-560f76816a2f',
        amount: 92875,
        discount_amount: 1000,
        total_discount_amount: 1000,
        total_amount: 91875,
        items: [
          {
            object: 'order_item',
            source_id: 'M0E20000000EE54',
            related_object: 'sku',
            quantity: 1,
            amount: 18500,
            price: 18500,
            subtotal_amount: 18500,
            product: { name: 'Jeans Cycle dark blue', override: true },
            sku: { sku: 'Jeans Cycle dark blue', metadata: {}, override: true },
          },
          {
            object: 'order_item',
            source_id: 'M0E20000000EE54',
            related_object: 'sku',
            quantity: 2,
            amount: 37000,
            price: 18500,
            subtotal_amount: 37000,
            product: { name: 'Jeans Cycle dark blue', override: true },
            sku: { sku: 'Jeans Cycle dark blue', metadata: {}, override: true },
          },
          {
            object: 'order_item',
            source_id: 'M0E20000000ELDI',
            related_object: 'sku',
            product_id: 'prod_0d1abfb839c51910d8',
            quantity: 1,
            amount: 37375,
            price: 37375,
            subtotal_amount: 37375,
            product: {
              id: 'prod_0d1abfb839c51910d8',
              source_id: '253ec97b-f8ac-4a14-94e2-150f5ab0510a',
              name: 'Casual jacket Michael Kors beige',
              override: true,
            },
            sku: {
              id: 'sku_0d1ac1959a4c544f3b',
              source_id: 'M0E20000000ELDI',
              sku: 'Casual jacket Michael Kors beige',
              metadata: {},
              price: 37375,
              override: true,
            },
          },
        ],
        metadata: {},
        customer_id: null,
        referrer_id: null,
        object: 'order',
      },
      applicable_to: {
        data: [
          {
            object: 'sku',
            id: 'sku_0d1ac195990c544f39',
            source_id: 'M0E20000000ELDG',
            product_id: 'prod_0d1abfb839c51910d8',
            product_source_id: '253ec97b-f8ac-4a14-94e2-150f5ab0510a',
            strict: true,
            effect: 'APPLY_TO_EVERY',
          },
        ],
        total: 1,
        data_ref: 'data',
        object: 'list',
      },
      inapplicable_to: { data: [], total: 0, data_ref: 'data', object: 'list' },
      result: {
        discount: {
          type: 'PERCENT',
          effect: 'APPLY_TO_ITEMS',
          percent_off: 10,
          is_dynamic: false,
        },
      },
    },
    {
      status: 'APPLICABLE',
      id: 'SET100FIXEDPRICE',
      object: 'voucher',
      order: {
        source_id: 'fd399771-99ee-4a69-9b87-560f76816a2f',
        amount: 92875,
        discount_amount: 1000,
        items_discount_amount: 27375,
        total_discount_amount: 28375,
        total_amount: 64500,
        items_applied_discount_amount: 27375,
        total_applied_discount_amount: 27375,
        items: [
          {
            object: 'order_item',
            source_id: 'M0E20000000EE54',
            related_object: 'sku',
            quantity: 1,
            amount: 18500,
            price: 18500,
            subtotal_amount: 18500,
            product: { name: 'Jeans Cycle dark blue', override: true },
            sku: { sku: 'Jeans Cycle dark blue', metadata: {}, override: true },
          },
          {
            object: 'order_item',
            source_id: 'M0E20000000EE54',
            related_object: 'sku',
            quantity: 2,
            amount: 37000,
            price: 18500,
            subtotal_amount: 37000,
            product: { name: 'Jeans Cycle dark blue', override: true },
            sku: { sku: 'Jeans Cycle dark blue', metadata: {}, override: true },
          },
          {
            object: 'order_item',
            source_id: 'M0E20000000ELDI',
            related_object: 'sku',
            product_id: 'prod_0d1abfb839c51910d8',
            quantity: 1,
            amount: 37375,
            discount_amount: 27375,
            applied_discount_amount: 27375,
            price: 37375,
            subtotal_amount: 10000,
            product: {
              id: 'prod_0d1abfb839c51910d8',
              source_id: '253ec97b-f8ac-4a14-94e2-150f5ab0510a',
              name: 'Casual jacket Michael Kors beige',
              override: true,
            },
            sku: {
              id: 'sku_0d1ac1959a4c544f3b',
              source_id: 'M0E20000000ELDI',
              sku: 'Casual jacket Michael Kors beige',
              metadata: {},
              price: 37375,
              override: true,
            },
          },
        ],
        metadata: {},
        customer_id: null,
        referrer_id: null,
        object: 'order',
      },
      applicable_to: {
        data: [
          {
            object: 'sku',
            id: 'sku_0d1ac1959a4c544f3b',
            source_id: 'M0E20000000ELDI',
            product_id: 'prod_0d1abfb839c51910d8',
            product_source_id: '253ec97b-f8ac-4a14-94e2-150f5ab0510a',
            strict: true,
            price: 10000,
            effect: 'APPLY_TO_EVERY',
            order_item_indices: [2],
          },
        ],
        total: 1,
        data_ref: 'data',
        object: 'list',
      },
      inapplicable_to: { data: [], total: 0, data_ref: 'data', object: 'list' },
      result: {
        discount: {
          type: 'FIXED',
          effect: 'APPLY_TO_ITEMS',
          is_dynamic: false,
        },
      },
    },
  ],
  inapplicableCoupons: [],
  newSessionKey: 'ssn_LaXruZ16YofEL1ZZIxXsWBCsxfpFGALb',
  totalDiscountAmount: 28375,
  productsToAdd: [],
  couponsLimit: 5,
  cartDiscountApplyMode: 0,
  commerceToolsCart: {
    type: 'Cart',
    id: 'fd399771-99ee-4a69-9b87-560f76816a2f',
    version: 82,
    versionModifiedAt: '2023-06-22T17:29:59.682Z',
    lastMessageSequenceNumber: 1,
    createdAt: '2023-06-22T16:55:32.015Z',
    lastModifiedAt: '2023-06-22T17:29:59.682Z',
    lastModifiedBy: {
      clientId: '3cx8PEBHMZQ1oHAYF1eoDs8i',
      isPlatformClient: false,
      anonymousId: '75db9a3a-094f-4195-96f0-2834f115997f',
    },
    createdBy: {
      clientId: '3cx8PEBHMZQ1oHAYF1eoDs8i',
      isPlatformClient: false,
      anonymousId: '75db9a3a-094f-4195-96f0-2834f115997f',
    },
    anonymousId: '75db9a3a-094f-4195-96f0-2834f115997f',
    lineItems: [
      {
        id: '093db141-0a2b-472d-b520-556b8c7ac307',
        productId: '73ce4f06-80ad-48e6-8b36-e7102fdc8709',
        productKey: '81338',
        name: { en: 'Jeans Cycle dark blue', de: 'Jeans Cycle dunkelblau' },
        productType: {
          typeId: 'product-type',
          id: 'f084fa3e-01bd-4ee2-8c8a-9a18764e8841',
          version: 1,
        },
        productSlug: {
          en: 'cycle-jeans-T225B0440880-darkblue',
          de: 'cycle-jeans-T225B0440880-dunkelblau',
        },
        variant: {
          id: 1,
          sku: 'M0E20000000EE54',
          key: 'M0E20000000EE54',
          prices: [
            {
              id: 'cc49dc1d-515b-4bf7-9a49-e0da4266d9dd',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 18500,
                fractionDigits: 2,
              },
            },
            {
              id: '3d14867a-66d2-4766-a05d-b66bfd258121',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 12131,
                fractionDigits: 2,
              },
              customerGroup: {
                typeId: 'customer-group',
                id: '0c826f37-d10d-439c-bf46-ce9e17deab74',
              },
            },
            {
              id: '1728926f-e928-4eba-8aab-8338406b0f38',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 18500,
                fractionDigits: 2,
              },
              country: 'US',
            },
            {
              id: '9e7124c7-fba6-4fe3-9b13-1262a74bf054',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 12131,
                fractionDigits: 2,
              },
              customerGroup: {
                typeId: 'customer-group',
                id: '0c826f37-d10d-439c-bf46-ce9e17deab74',
              },
            },
            {
              id: '268bd270-188d-480e-91ce-62f5ce36cd44',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 14800,
                fractionDigits: 2,
              },
              country: 'DE',
            },
            {
              id: '79e2adaf-1f35-44cf-b6b6-959730676fe2',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 14800,
                fractionDigits: 2,
              },
              country: 'IT',
            },
            {
              id: '4a76b969-9927-4499-95f3-70ba1986d792',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 14800,
                fractionDigits: 2,
              },
              country: 'GB',
            },
            {
              id: '85475aaa-0a2a-4469-a766-1f214477c7c6',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 16132,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'd4e8a815-830f-43bf-8506-77de565bf3f3',
              },
            },
            {
              id: 'ea15846d-304b-492c-bf9a-4f203d3ce218',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 20165,
                fractionDigits: 2,
              },
              channel: {
                typeId: 'channel',
                id: '68506b79-8d88-47ab-b77d-5b54cb6eec03',
              },
            },
            {
              id: '1f7c4b96-faa9-4042-b7b7-a06cc00659dd',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 16280,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: '075f15ed-e66a-49a6-8d61-786145ac1a7a',
              },
            },
            {
              id: 'e7c79b01-130c-4e3b-8b9e-0e014a18f885',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 13468,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'ffecbfe5-a622-4e1f-8704-ac328d94cfb5',
              },
            },
            {
              id: 'bcdbfe78-1906-445d-882e-cf4431eb84df',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 13616,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'c9958b11-6151-433e-83f3-4424e6fa4ac2',
              },
            },
            {
              id: '6a68bc68-3fe4-42fe-aa84-eb9efe201a23',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 16132,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: '2259d32b-2c7a-4941-842a-d81fb3c878e7',
              },
            },
            {
              id: '33958888-3989-49db-b64e-124fd35aacc4',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 20165,
                fractionDigits: 2,
              },
              channel: {
                typeId: 'channel',
                id: '0399ae91-a3be-40ef-90cc-11ac36cf8a62',
              },
            },
            {
              id: '76ed4a2f-ea55-4d05-8393-1616dca4c679',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 16280,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: 'bcaecbbd-bf7c-4f9f-9b4b-c0cbd6240d68',
              },
            },
            {
              id: 'dae9fff7-75f0-479e-83a7-d4465b10bcdc',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 13468,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: '3def0285-22e1-401c-916b-56efb977f18e',
              },
            },
            {
              id: 'b22ac8dc-c357-45d9-97d5-9d7f4aeff564',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 13616,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: 'db86818a-f58b-4df4-8b61-46de85d13a00',
              },
            },
          ],
          images: [
            {
              url: 'https://s3-eu-west-1.amazonaws.com/commercetools-maximilian/products/081338_1_large.jpg',
              dimensions: { w: 0, h: 0 },
            },
          ],
          attributes: [
            {
              name: 'articleNumberManufacturer',
              value: 'WPT492 T225 B044 0880 001',
            },
            { name: 'articleNumberMax', value: '81338' },
            { name: 'matrixId', value: 'M0E20000000EE54' },
            { name: 'baseId', value: '81338' },
            { name: 'designer', value: { key: 'cycle', label: 'Cycle' } },
            { name: 'madeInItaly', value: { key: 'yes', label: 'yes' } },
            { name: 'commonSize', value: { key: 'xxs', label: 'XXS' } },
            { name: 'size', value: '24' },
            {
              name: 'color',
              value: {
                key: 'blue',
                label: { de: 'blau', it: 'blu', en: 'blue' },
              },
            },
            {
              name: 'colorFreeDefinition',
              value: { en: 'dark blue', de: 'dunkelblau' },
            },
            { name: 'style', value: { key: 'sporty', label: 'sporty' } },
            { name: 'gender', value: { key: 'women', label: 'Damen' } },
            { name: 'season', value: 's15' },
          ],
          assets: [],
        },
        price: {
          id: '1728926f-e928-4eba-8aab-8338406b0f38',
          value: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 18500,
            fractionDigits: 2,
          },
          country: 'US',
        },
        quantity: 1,
        discountedPricePerQuantity: [],
        taxRate: {
          name: '10% incl.',
          amount: 0.1,
          includedInPrice: true,
          country: 'US',
          id: '_JMEWRo5',
          subRates: [],
        },
        perMethodTaxRate: [],
        addedAt: '2023-06-22T16:55:32.153Z',
        lastModifiedAt: '2023-06-22T16:55:32.153Z',
        state: [
          {
            quantity: 1,
            state: {
              typeId: 'state',
              id: 'ad3930da-ae5c-4c7e-8ae0-2dfb99d52f50',
            },
          },
        ],
        priceMode: 'Platform',
        lineItemMode: 'Standard',
        totalPrice: {
          type: 'centPrecision',
          currencyCode: 'USD',
          centAmount: 18500,
          fractionDigits: 2,
        },
        taxedPrice: {
          totalNet: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 16818,
            fractionDigits: 2,
          },
          totalGross: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 18500,
            fractionDigits: 2,
          },
          totalTax: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 1682,
            fractionDigits: 2,
          },
        },
        taxedPricePortions: [],
        custom: {
          type: { typeId: 'type', id: '69840f60-bd39-4958-b3fc-85bf6c492791' },
          fields: {},
        },
      },
      {
        id: '883ca605-dcb1-4f83-84e4-d75742bd38f8',
        productId: '73ce4f06-80ad-48e6-8b36-e7102fdc8709',
        productKey: '81338',
        name: { en: 'Jeans Cycle dark blue', de: 'Jeans Cycle dunkelblau' },
        productType: {
          typeId: 'product-type',
          id: 'f084fa3e-01bd-4ee2-8c8a-9a18764e8841',
          version: 1,
        },
        productSlug: {
          en: 'cycle-jeans-T225B0440880-darkblue',
          de: 'cycle-jeans-T225B0440880-dunkelblau',
        },
        variant: {
          id: 1,
          sku: 'M0E20000000EE54',
          key: 'M0E20000000EE54',
          prices: [
            {
              id: 'cc49dc1d-515b-4bf7-9a49-e0da4266d9dd',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 18500,
                fractionDigits: 2,
              },
            },
            {
              id: '3d14867a-66d2-4766-a05d-b66bfd258121',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 12131,
                fractionDigits: 2,
              },
              customerGroup: {
                typeId: 'customer-group',
                id: '0c826f37-d10d-439c-bf46-ce9e17deab74',
              },
            },
            {
              id: '1728926f-e928-4eba-8aab-8338406b0f38',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 18500,
                fractionDigits: 2,
              },
              country: 'US',
            },
            {
              id: '9e7124c7-fba6-4fe3-9b13-1262a74bf054',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 12131,
                fractionDigits: 2,
              },
              customerGroup: {
                typeId: 'customer-group',
                id: '0c826f37-d10d-439c-bf46-ce9e17deab74',
              },
            },
            {
              id: '268bd270-188d-480e-91ce-62f5ce36cd44',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 14800,
                fractionDigits: 2,
              },
              country: 'DE',
            },
            {
              id: '79e2adaf-1f35-44cf-b6b6-959730676fe2',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 14800,
                fractionDigits: 2,
              },
              country: 'IT',
            },
            {
              id: '4a76b969-9927-4499-95f3-70ba1986d792',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 14800,
                fractionDigits: 2,
              },
              country: 'GB',
            },
            {
              id: '85475aaa-0a2a-4469-a766-1f214477c7c6',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 16132,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'd4e8a815-830f-43bf-8506-77de565bf3f3',
              },
            },
            {
              id: 'ea15846d-304b-492c-bf9a-4f203d3ce218',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 20165,
                fractionDigits: 2,
              },
              channel: {
                typeId: 'channel',
                id: '68506b79-8d88-47ab-b77d-5b54cb6eec03',
              },
            },
            {
              id: '1f7c4b96-faa9-4042-b7b7-a06cc00659dd',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 16280,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: '075f15ed-e66a-49a6-8d61-786145ac1a7a',
              },
            },
            {
              id: 'e7c79b01-130c-4e3b-8b9e-0e014a18f885',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 13468,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'ffecbfe5-a622-4e1f-8704-ac328d94cfb5',
              },
            },
            {
              id: 'bcdbfe78-1906-445d-882e-cf4431eb84df',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 13616,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'c9958b11-6151-433e-83f3-4424e6fa4ac2',
              },
            },
            {
              id: '6a68bc68-3fe4-42fe-aa84-eb9efe201a23',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 16132,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: '2259d32b-2c7a-4941-842a-d81fb3c878e7',
              },
            },
            {
              id: '33958888-3989-49db-b64e-124fd35aacc4',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 20165,
                fractionDigits: 2,
              },
              channel: {
                typeId: 'channel',
                id: '0399ae91-a3be-40ef-90cc-11ac36cf8a62',
              },
            },
            {
              id: '76ed4a2f-ea55-4d05-8393-1616dca4c679',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 16280,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: 'bcaecbbd-bf7c-4f9f-9b4b-c0cbd6240d68',
              },
            },
            {
              id: 'dae9fff7-75f0-479e-83a7-d4465b10bcdc',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 13468,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: '3def0285-22e1-401c-916b-56efb977f18e',
              },
            },
            {
              id: 'b22ac8dc-c357-45d9-97d5-9d7f4aeff564',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 13616,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: 'db86818a-f58b-4df4-8b61-46de85d13a00',
              },
            },
          ],
          images: [
            {
              url: 'https://s3-eu-west-1.amazonaws.com/commercetools-maximilian/products/081338_1_large.jpg',
              dimensions: { w: 0, h: 0 },
            },
          ],
          attributes: [
            {
              name: 'articleNumberManufacturer',
              value: 'WPT492 T225 B044 0880 001',
            },
            { name: 'articleNumberMax', value: '81338' },
            { name: 'matrixId', value: 'M0E20000000EE54' },
            { name: 'baseId', value: '81338' },
            { name: 'designer', value: { key: 'cycle', label: 'Cycle' } },
            { name: 'madeInItaly', value: { key: 'yes', label: 'yes' } },
            { name: 'commonSize', value: { key: 'xxs', label: 'XXS' } },
            { name: 'size', value: '24' },
            {
              name: 'color',
              value: {
                key: 'blue',
                label: { de: 'blau', it: 'blu', en: 'blue' },
              },
            },
            {
              name: 'colorFreeDefinition',
              value: { en: 'dark blue', de: 'dunkelblau' },
            },
            { name: 'style', value: { key: 'sporty', label: 'sporty' } },
            { name: 'gender', value: { key: 'women', label: 'Damen' } },
            { name: 'season', value: 's15' },
          ],
          assets: [],
        },
        price: {
          id: '1728926f-e928-4eba-8aab-8338406b0f38',
          value: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 18500,
            fractionDigits: 2,
          },
          country: 'US',
        },
        quantity: 2,
        discountedPricePerQuantity: [],
        taxRate: {
          name: '10% incl.',
          amount: 0.1,
          includedInPrice: true,
          country: 'US',
          id: '_JMEWRo5',
          subRates: [],
        },
        perMethodTaxRate: [],
        addedAt: '2023-06-22T16:55:34.290Z',
        lastModifiedAt: '2023-06-22T16:56:42.168Z',
        state: [
          {
            quantity: 2,
            state: {
              typeId: 'state',
              id: 'ad3930da-ae5c-4c7e-8ae0-2dfb99d52f50',
            },
          },
        ],
        priceMode: 'Platform',
        lineItemMode: 'Standard',
        totalPrice: {
          type: 'centPrecision',
          currencyCode: 'USD',
          centAmount: 37000,
          fractionDigits: 2,
        },
        taxedPrice: {
          totalNet: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 33636,
            fractionDigits: 2,
          },
          totalGross: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 37000,
            fractionDigits: 2,
          },
          totalTax: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 3364,
            fractionDigits: 2,
          },
        },
        taxedPricePortions: [],
        custom: {
          type: { typeId: 'type', id: '69840f60-bd39-4958-b3fc-85bf6c492791' },
          fields: {},
        },
      },
      {
        id: '86a2607b-55cb-4ea6-8d00-3cc53c4a2c33',
        productId: '253ec97b-f8ac-4a14-94e2-150f5ab0510a',
        productKey: '82378',
        name: {
          en: 'Casual jacket Michael Kors beige',
          de: 'Freizeitjacke Michael Kors beige',
        },
        productType: {
          typeId: 'product-type',
          id: 'f084fa3e-01bd-4ee2-8c8a-9a18764e8841',
          version: 1,
        },
        productSlug: {
          en: 'michael-kors-casualjacket-CS52DHK2J1-beige',
          de: 'michael-kors-freizeitjacke-CS52DHK2J1-beige',
        },
        variant: {
          id: 8,
          sku: 'M0E20000000ELDI',
          key: 'M0E20000000ELDI',
          prices: [
            {
              id: '8b23d5c9-ba2c-496f-922e-41cf588cb41e',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 37375,
                fractionDigits: 2,
              },
            },
            {
              id: '7fb8f742-6cce-4f0b-a0e5-3682e37ffd43',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 24508,
                fractionDigits: 2,
              },
              customerGroup: {
                typeId: 'customer-group',
                id: '0c826f37-d10d-439c-bf46-ce9e17deab74',
              },
            },
            {
              id: '459d2acc-a2ad-4c78-af36-e9fe3e480119',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 37375,
                fractionDigits: 2,
              },
              country: 'US',
            },
            {
              id: '7192109e-1d78-47f7-a54a-d3f96660ba57',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 24508,
                fractionDigits: 2,
              },
              customerGroup: {
                typeId: 'customer-group',
                id: '0c826f37-d10d-439c-bf46-ce9e17deab74',
              },
            },
            {
              id: '7b772656-2f02-4c9c-9d07-3cede836085e',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 29900,
                fractionDigits: 2,
              },
              country: 'DE',
            },
            {
              id: '130ed89e-c02a-4742-a802-5070278a20e0',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 29900,
                fractionDigits: 2,
              },
              country: 'IT',
            },
            {
              id: 'eb97d983-a04e-4896-b4d2-0d5bb654d4fd',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 29900,
                fractionDigits: 2,
              },
              country: 'GB',
            },
            {
              id: '1c99efd4-783c-4d3a-8ad3-e5a7513bb89b',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 32890,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'd4e8a815-830f-43bf-8506-77de565bf3f3',
              },
            },
            {
              id: 'bef86f7e-bf1f-4689-b7b3-50c3db6759b5',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 39618,
                fractionDigits: 2,
              },
              channel: {
                typeId: 'channel',
                id: '68506b79-8d88-47ab-b77d-5b54cb6eec03',
              },
            },
            {
              id: '9879cb7d-ab8e-441e-b03c-704f49cddc8b',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 27508,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: '075f15ed-e66a-49a6-8d61-786145ac1a7a',
              },
            },
            {
              id: 'c99b0708-2ef7-4f93-a2e1-1d75833db848',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 29601,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'ffecbfe5-a622-4e1f-8704-ac328d94cfb5',
              },
            },
            {
              id: '11200145-4068-42a9-b7dd-d95805ceae6c',
              value: {
                type: 'centPrecision',
                currencyCode: 'EUR',
                centAmount: 28405,
                fractionDigits: 2,
              },
              country: 'DE',
              channel: {
                typeId: 'channel',
                id: 'c9958b11-6151-433e-83f3-4424e6fa4ac2',
              },
            },
            {
              id: 'fd42e5fd-f1fc-4447-a120-005ad8e5b786',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 32890,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: '2259d32b-2c7a-4941-842a-d81fb3c878e7',
              },
            },
            {
              id: '0319cf26-7d6b-4abd-b082-863875de6de9',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 39618,
                fractionDigits: 2,
              },
              channel: {
                typeId: 'channel',
                id: '0399ae91-a3be-40ef-90cc-11ac36cf8a62',
              },
            },
            {
              id: '5ece5297-ebad-4077-a50c-fdc204c85fd6',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 27508,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: 'bcaecbbd-bf7c-4f9f-9b4b-c0cbd6240d68',
              },
            },
            {
              id: '6afbdff5-616b-4416-951c-1755fe120656',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 29601,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: '3def0285-22e1-401c-916b-56efb977f18e',
              },
            },
            {
              id: '89ef1122-3115-4816-8b93-57a0b3ea1c26',
              value: {
                type: 'centPrecision',
                currencyCode: 'USD',
                centAmount: 28405,
                fractionDigits: 2,
              },
              country: 'US',
              channel: {
                typeId: 'channel',
                id: 'db86818a-f58b-4df4-8b61-46de85d13a00',
              },
            },
          ],
          images: [
            {
              url: 'https://s3-eu-west-1.amazonaws.com/commercetools-maximilian/products/082378_1_medium.jpg',
              dimensions: { w: 0, h: 0 },
            },
          ],
          attributes: [
            { name: 'articleNumberManufacturer', value: 'CS52DHK2J1 275' },
            { name: 'articleNumberMax', value: '82378' },
            { name: 'matrixId', value: 'M0E20000000ELDI' },
            { name: 'baseId', value: '82378' },
            {
              name: 'designer',
              value: { key: 'michaelkors', label: 'Michael Kors' },
            },
            { name: 'madeInItaly', value: { key: 'no', label: 'no' } },
            { name: 'commonSize', value: { key: 'xxxl', label: 'XXXL' } },
            { name: 'size', value: 'XXXL' },
            {
              name: 'color',
              value: {
                key: 'beige',
                label: { it: 'beige', de: 'beige', en: 'beige' },
              },
            },
            {
              name: 'colorFreeDefinition',
              value: { en: 'beige', de: 'beige' },
            },
            { name: 'style', value: { key: 'sporty', label: 'sporty' } },
            { name: 'gender', value: { key: 'men', label: 'Herren' } },
            { name: 'season', value: 's15' },
          ],
          assets: [],
        },
        price: {
          id: '459d2acc-a2ad-4c78-af36-e9fe3e480119',
          value: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 37375,
            fractionDigits: 2,
          },
          country: 'US',
        },
        quantity: 1,
        discountedPricePerQuantity: [],
        taxRate: {
          name: '10% incl.',
          amount: 0.1,
          includedInPrice: true,
          country: 'US',
          id: '_JMEWRo5',
          subRates: [],
        },
        perMethodTaxRate: [],
        addedAt: '2023-06-22T17:23:04.195Z',
        lastModifiedAt: '2023-06-22T17:29:59.669Z',
        state: [
          {
            quantity: 1,
            state: {
              typeId: 'state',
              id: 'ad3930da-ae5c-4c7e-8ae0-2dfb99d52f50',
            },
          },
        ],
        priceMode: 'Platform',
        lineItemMode: 'Standard',
        totalPrice: {
          type: 'centPrecision',
          currencyCode: 'USD',
          centAmount: 37375,
          fractionDigits: 2,
        },
        taxedPrice: {
          totalNet: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 33977,
            fractionDigits: 2,
          },
          totalGross: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 37375,
            fractionDigits: 2,
          },
          totalTax: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 3398,
            fractionDigits: 2,
          },
        },
        taxedPricePortions: [],
        custom: {
          type: { typeId: 'type', id: '69840f60-bd39-4958-b3fc-85bf6c492791' },
          fields: { applied_codes: [] },
        },
      },
    ],
    cartState: 'Active',
    totalPrice: {
      type: 'centPrecision',
      currencyCode: 'USD',
      centAmount: 91875,
      fractionDigits: 2,
    },
    taxedPrice: {
      totalNet: {
        type: 'centPrecision',
        currencyCode: 'USD',
        centAmount: 83431,
        fractionDigits: 2,
      },
      totalGross: {
        type: 'centPrecision',
        currencyCode: 'USD',
        centAmount: 91875,
        fractionDigits: 2,
      },
      taxPortions: [
        {
          rate: 0,
          amount: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 0,
            fractionDigits: 2,
          },
          name: 'coupon',
        },
        {
          rate: 0.1,
          amount: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 8444,
            fractionDigits: 2,
          },
          name: '10% incl.',
        },
      ],
      totalTax: {
        type: 'centPrecision',
        currencyCode: 'USD',
        centAmount: 8444,
        fractionDigits: 2,
      },
    },
    country: 'US',
    shippingMode: 'Single',
    shippingAddress: { country: 'US' },
    shipping: [],
    customLineItems: [
      {
        totalPrice: {
          type: 'centPrecision',
          currencyCode: 'USD',
          centAmount: -1000,
          fractionDigits: 2,
        },
        id: '188c5daf-1ce0-4eb0-9120-8eebdff7f796',
        name: { en: 'Coupon codes discount', de: 'Gutscheincodes rabatt' },
        money: {
          type: 'centPrecision',
          currencyCode: 'USD',
          centAmount: -1000,
          fractionDigits: 2,
        },
        slug: 'Voucher, ',
        quantity: 1,
        discountedPricePerQuantity: [],
        taxCategory: {
          typeId: 'tax-category',
          id: '1f84a16d-00b2-42c3-9367-a7a31bf2ebce',
        },
        taxRate: {
          name: 'coupon',
          amount: 0,
          includedInPrice: true,
          country: 'US',
          id: 'Uw-uqD9r',
          subRates: [],
        },
        state: [
          {
            quantity: 1,
            state: {
              typeId: 'state',
              id: 'ad3930da-ae5c-4c7e-8ae0-2dfb99d52f50',
            },
          },
        ],
        taxedPrice: {
          totalNet: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: -1000,
            fractionDigits: 2,
          },
          totalGross: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: -1000,
            fractionDigits: 2,
          },
          totalTax: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 0,
            fractionDigits: 2,
          },
        },
        perMethodTaxRate: [],
        priceMode: 'Standard',
      },
    ],
    discountCodes: [],
    directDiscounts: [],
    custom: {
      type: { typeId: 'type', id: '22ec137d-4ea0-468f-98e9-f9289ca8bb01' },
      fields: {
        couponsLimit: 5,
        discount_codes: [
          '{"code":"10off","status":"APPLIED","type":"voucher","value":1000}',
          '{"code":"10OFFITEM","status":"APPLIED","type":"voucher","value":1000}',
          '{"code":"SET100FIXEDPRICE","status":"NEW"}',
        ],
        shippingProductSourceIds: [],
        session: 'ssn_LaXruZ16YofEL1ZZIxXsWBCsxfpFGALb',
      },
    },
    inventoryMode: 'None',
    taxMode: 'Platform',
    taxRoundingMode: 'HalfEven',
    taxCalculationMode: 'LineItemLevel',
    deleteDaysAfterLastModification: 90,
    refusedGifts: [],
    origin: 'Customer',
    itemShippingAddresses: [],
    totalLineItemQuantity: 4,
  },
  taxCategory: {
    id: '1f84a16d-00b2-42c3-9367-a7a31bf2ebce',
    version: 5,
    versionModifiedAt: '2023-05-31T16:04:06.867Z',
    createdAt: '2023-05-31T16:04:06.656Z',
    lastModifiedAt: '2023-05-31T16:04:06.867Z',
    lastModifiedBy: {
      clientId: '3cx8PEBHMZQ1oHAYF1eoDs8i',
      isPlatformClient: false,
    },
    createdBy: {
      clientId: '3cx8PEBHMZQ1oHAYF1eoDs8i',
      isPlatformClient: false,
    },
    name: 'coupon',
    rates: [
      {
        name: 'coupon',
        amount: 0,
        includedInPrice: true,
        country: 'DE',
        id: '3SF4_HMk',
        subRates: [],
      },
      {
        name: 'coupon',
        amount: 0,
        includedInPrice: true,
        country: 'AT',
        id: 'lRz7jEYP',
        subRates: [],
      },
      {
        name: 'coupon',
        amount: 0,
        includedInPrice: true,
        country: 'US',
        id: 'Uw-uqD9r',
        subRates: [],
      },
      {
        name: 'coupon',
        amount: 0,
        includedInPrice: true,
        country: 'NL',
        id: 'StiKGNhA',
        subRates: [],
      },
    ],
  },
};
