export const promotions = [
  {
    valid: true,
    applicable_to: {
      data: [],
      total: 0,
      data_ref: 'data',
      object: 'list',
    },
    inapplicable_to: {
      data: [],
      total: 0,
      data_ref: 'data',
      object: 'list',
    },
    tracking_id:
      'track_7WIx4VHJ3kH9Eq0l7vviiBE4gf0jaFOq1qD3I47SdJUwE17T14L2tw==',
    order: {
      source_id: 'e88e7200-48f1-4bbb-b0a1-af26aace78d8',
      amount: 106000,
      discount_amount: 1000,
      total_discount_amount: 1000,
      total_amount: 105000,
      applied_discount_amount: 1000,
      total_applied_discount_amount: 1000,
      items: [
        {
          object: 'order_item',
          source_id: 'M0E20000000DUIR',
          related_object: 'sku',
          quantity: 4,
          amount: 106000,
          price: 26500,
          subtotal_amount: 106000,
          product: {
            name: 'Pants Jacob Cohen green',
            override: true,
          },
          sku: {
            sku: 'Pants Jacob Cohen green',
            metadata: {},
            override: true,
          },
        },
      ],
      metadata: {},
      customer_id: null,
      referrer_id: null,
      object: 'order',
    },
    id: 'promo_LP8KQR34UHK5b1UWeBH62FS2',
    name: 'Promotion A2 tier 1',
    banner: 'Promotion A2 tier 1',
    discount: {
      type: 'AMOUNT',
      effect: 'APPLY_TO_ORDER',
      amount_off: 1000,
      is_dynamic: false,
    },
    campaign: {
      id: 'camp_vfXIzAr1MtiFsdqtu482tX0f',
      start_date: null,
      expiration_date: null,
      active: true,
      object: 'campaign',
    },
    hierarchy: 1,
    discount_amount: 1000,
    applied_discount_amount: 1000,
    metadata: {},
    object: 'promotion_tier',
    category_id: null,
    categories: [],
  },
  {
    valid: true,
    applicable_to: {
      data: [],
      total: 0,
      data_ref: 'data',
      object: 'list',
    },
    inapplicable_to: {
      data: [],
      total: 0,
      data_ref: 'data',
      object: 'list',
    },
    tracking_id:
      'track_7WIx4VHJ3kH9Eq0l7vviiBE4gf0jaFOq1qD3I47SdJUwE17T14L2tw==',
    order: {
      source_id: 'e88e7200-48f1-4bbb-b0a1-af26aace78d8',
      amount: 106000,
      discount_amount: 1000,
      total_discount_amount: 1000,
      total_amount: 105000,
      applied_discount_amount: 1000,
      total_applied_discount_amount: 1000,
      items: [
        {
          object: 'order_item',
          source_id: 'M0E20000000DUIR',
          related_object: 'sku',
          quantity: 4,
          amount: 106000,
          price: 26500,
          subtotal_amount: 106000,
          product: {
            name: 'Pants Jacob Cohen green',
            override: true,
          },
          sku: {
            sku: 'Pants Jacob Cohen green',
            metadata: {},
            override: true,
          },
        },
      ],
      metadata: {},
      customer_id: null,
      referrer_id: null,
      object: 'order',
    },
    id: 'promo_Y4lMzNB8H69GojnLyF3hJZXP',
    name: 'Promotion A1 tier 1',
    banner: 'Promotion A1 tier 1',
    discount: {
      type: 'AMOUNT',
      effect: 'APPLY_TO_ORDER',
      amount_off: 1000,
      is_dynamic: false,
    },
    campaign: {
      id: 'camp_T6XdWJdP6zvTnCwmgNLoLut3',
      start_date: null,
      expiration_date: null,
      active: true,
      object: 'campaign',
    },
    hierarchy: 1,
    discount_amount: 1000,
    applied_discount_amount: 1000,
    metadata: {},
    object: 'promotion_tier',
    category_id: null,
    categories: [],
  },
  {
    valid: true,
    applicable_to: {
      data: [],
      total: 0,
      data_ref: 'data',
      object: 'list',
    },
    inapplicable_to: {
      data: [],
      total: 0,
      data_ref: 'data',
      object: 'list',
    },
    tracking_id:
      'track_7WIx4VHJ3kH9Eq0l7vviiBE4gf0jaFOq1qD3I47SdJUwE17T14L2tw==',
    order: {
      source_id: 'e88e7200-48f1-4bbb-b0a1-af26aace78d8',
      amount: 106000,
      discount_amount: 10600,
      total_discount_amount: 10600,
      total_amount: 95400,
      applied_discount_amount: 10600,
      total_applied_discount_amount: 10600,
      items: [
        {
          object: 'order_item',
          source_id: 'M0E20000000DUIR',
          related_object: 'sku',
          quantity: 4,
          amount: 106000,
          price: 26500,
          subtotal_amount: 106000,
          product: {
            name: 'Pants Jacob Cohen green',
            override: true,
          },
          sku: {
            sku: 'Pants Jacob Cohen green',
            metadata: {},
            override: true,
          },
        },
      ],
      metadata: {},
      customer_id: null,
      referrer_id: null,
      object: 'order',
    },
    id: 'promo_O2WtQixJ6WbXy0KRNG24S51Y',
    name: 'Over 300EUR off',
    banner: 'Over 300EUR off',
    discount: {
      type: 'PERCENT',
      effect: 'APPLY_TO_ORDER',
      percent_off: 10,
      amount_limit: 100000,
      is_dynamic: false,
    },
    campaign: {
      id: 'camp_3oe5B5ZGhn3tqtJzQ2ca9mJL',
      start_date: null,
      expiration_date: null,
      active: true,
      object: 'campaign',
    },
    hierarchy: 1,
    discount_amount: 10600,
    applied_discount_amount: 10600,
    metadata: {},
    object: 'promotion_tier',
    category_id: null,
    categories: [],
  },
];
