export const voucherifyResponse = {
  valid: true,
  redeemables: [
    {
      status: 'APPLICABLE',
      id: '30%off',
      object: 'voucher',
      order: {
        source_id: 'a5a350ac-f538-42e4-9f23-e0df0cb37561',
        amount: 170900,
        discount_amount: 51270,
        total_discount_amount: 51270,
        total_amount: 119630,
        applied_discount_amount: 51270,
        total_applied_discount_amount: 51270,
        items: [
          {
            object: 'order_item',
            source_id: 'M0E20000000DUIR',
            related_object: 'sku',
            quantity: 4,
            amount: 106000,
            price: 26500,
            subtotal_amount: 106000,
            product: {
              name: 'Pants Jacob Cohen green',
              override: true,
            },
            sku: {
              sku: 'Pants Jacob Cohen green',
              metadata: {},
              override: true,
            },
          },
          {
            object: 'order_item',
            source_id: 'A0E200000001UTR',
            related_object: 'sku',
            product_id: 'prod_0b661d35bf8b29a1ee',
            quantity: 1,
            amount: 64900,
            price: 64900,
            subtotal_amount: 64900,
            product: {
              id: 'prod_0b661d35bf8b29a1ee',
              source_id: '8196593a-7e3e-464f-95eb-ccfdc5e51a35',
              name: 'Handbag by Karl Lagerfeld',
              override: true,
            },
            sku: {
              id: 'sku_0b661d89b787ec1b6d',
              source_id: 'A0E200000001UTR',
              sku: 'Handbag by Karl Lagerfeld',
              metadata: {},
              price: 64900,
              override: true,
            },
          },
        ],
        metadata: {},
        customer_id: null,
        referrer_id: null,
        object: 'order',
      },
      applicable_to: {
        data: [],
        total: 0,
        data_ref: 'data',
        object: 'list',
      },
      inapplicable_to: {
        data: [],
        total: 0,
        data_ref: 'data',
        object: 'list',
      },
      result: {
        discount: {
          type: 'PERCENT',
          effect: 'APPLY_TO_ORDER',
          percent_off: 30,
          is_dynamic: false,
        },
      },
    },
    {
      status: 'APPLICABLE',
      id: 'unit_off_1',
      object: 'voucher',
      order: {
        source_id: 'a5a350ac-f538-42e4-9f23-e0df0cb37561',
        amount: 170900,
        initial_amount: 170900,
        discount_amount: 51270,
        items_discount_amount: 64900,
        total_discount_amount: 116170,
        total_amount: 54730,
        items_applied_discount_amount: 64900,
        total_applied_discount_amount: 64900,
        items: [
          {
            object: 'order_item',
            source_id: 'M0E20000000DUIR',
            related_object: 'sku',
            quantity: 4,
            amount: 106000,
            price: 26500,
            subtotal_amount: 106000,
            product: {
              name: 'Pants Jacob Cohen green',
              override: true,
            },
            sku: {
              sku: 'Pants Jacob Cohen green',
              metadata: {},
              override: true,
            },
          },
          {
            object: 'order_item',
            source_id: 'A0E200000001UTR',
            related_object: 'sku',
            product_id: 'prod_0b661d35bf8b29a1ee',
            quantity: 1,
            discount_quantity: 1,
            initial_quantity: 1,
            amount: 64900,
            discount_amount: 64900,
            initial_amount: 64900,
            applied_discount_amount: 64900,
            price: 64900,
            subtotal_amount: 0,
            product: {
              id: 'prod_0b661d35bf8b29a1ee',
              source_id: '8196593a-7e3e-464f-95eb-ccfdc5e51a35',
              name: 'Handbag by Karl Lagerfeld',
              override: true,
            },
            sku: {
              id: 'sku_0b661d89b787ec1b6d',
              source_id: 'A0E200000001UTR',
              sku: 'Handbag by Karl Lagerfeld',
              metadata: {},
              price: 64900,
              override: true,
            },
          },
        ],
        metadata: {},
        customer_id: null,
        referrer_id: null,
        object: 'order',
      },
      applicable_to: {
        data: [],
        total: 0,
        data_ref: 'data',
        object: 'list',
      },
      inapplicable_to: {
        data: [],
        total: 0,
        data_ref: 'data',
        object: 'list',
      },
      result: {
        discount: {
          type: 'UNIT',
          effect: 'ADD_MISSING_ITEMS',
          unit_off: 1,
          unit_type: 'sku_0b661d89b787ec1b6d',
          sku: {
            id: 'sku_0b661d89b787ec1b6d',
            source_id: 'A0E200000001UTR',
            sku: 'Handbag by Karl Lagerfeld',
          },
          product: {
            id: 'prod_0b661d35bf8b29a1ee',
            source_id: '8196593a-7e3e-464f-95eb-ccfdc5e51a35',
            name: 'Handbag by Karl Lagerfeld',
          },
          is_dynamic: false,
        },
      },
    },
    {
      status: 'APPLICABLE',
      id: '10off-Handbag',
      object: 'voucher',
      order: {
        source_id: 'a5a350ac-f538-42e4-9f23-e0df0cb37561',
        amount: 170900,
        discount_amount: 51270,
        items_discount_amount: 64900,
        total_discount_amount: 116170,
        total_amount: 54730,
        items_applied_discount_amount: 0,
        total_applied_discount_amount: 0,
        items: [
          {
            object: 'order_item',
            source_id: 'M0E20000000DUIR',
            related_object: 'sku',
            quantity: 4,
            amount: 106000,
            price: 26500,
            subtotal_amount: 106000,
            product: {
              name: 'Pants Jacob Cohen green',
              override: true,
            },
            sku: {
              sku: 'Pants Jacob Cohen green',
              metadata: {},
              override: true,
            },
          },
          {
            object: 'order_item',
            source_id: 'A0E200000001UTR',
            related_object: 'sku',
            product_id: 'prod_0b661d35bf8b29a1ee',
            quantity: 1,
            discount_quantity: 1,
            initial_quantity: 1,
            amount: 64900,
            discount_amount: 64900,
            initial_amount: 64900,
            applied_discount_amount: 0,
            price: 64900,
            subtotal_amount: 0,
            product: {
              id: 'prod_0b661d35bf8b29a1ee',
              source_id: '8196593a-7e3e-464f-95eb-ccfdc5e51a35',
              name: 'Handbag by Karl Lagerfeld',
              override: true,
            },
            sku: {
              id: 'sku_0b661d89b787ec1b6d',
              source_id: 'A0E200000001UTR',
              sku: 'Handbag by Karl Lagerfeld',
              metadata: {},
              price: 64900,
              override: true,
            },
          },
        ],
        metadata: {},
        customer_id: null,
        referrer_id: null,
        object: 'order',
      },
      applicable_to: {
        data: [
          {
            object: 'sku',
            id: 'sku_0b661d89b787ec1b6d',
            source_id: 'A0E200000001UTR',
            product_id: 'prod_0b661d35bf8b29a1ee',
            product_source_id: '8196593a-7e3e-464f-95eb-ccfdc5e51a35',
            strict: true,
            effect: 'APPLY_TO_EVERY',
            order_item_indices: [1],
          },
        ],
        total: 1,
        data_ref: 'data',
        object: 'list',
      },
      inapplicable_to: {
        data: [],
        total: 0,
        data_ref: 'data',
        object: 'list',
      },
      result: {
        discount: {
          type: 'AMOUNT',
          effect: 'APPLY_TO_ITEMS',
          amount_off: 1000,
          is_dynamic: false,
        },
      },
    },
  ],
  order: {
    source_id: 'a5a350ac-f538-42e4-9f23-e0df0cb37561',
    amount: 170900,
    discount_amount: 51270,
    items_discount_amount: 64900,
    total_discount_amount: 116170,
    total_amount: 54730,
    applied_discount_amount: 51270,
    items_applied_discount_amount: 64900,
    total_applied_discount_amount: 116170,
    items: [
      {
        object: 'order_item',
        source_id: 'M0E20000000DUIR',
        related_object: 'sku',
        quantity: 4,
        amount: 106000,
        price: 26500,
        subtotal_amount: 106000,
        product: {
          name: 'Pants Jacob Cohen green',
          override: true,
        },
        sku: {
          sku: 'Pants Jacob Cohen green',
          metadata: {},
          override: true,
        },
      },
      {
        object: 'order_item',
        source_id: 'A0E200000001UTR',
        related_object: 'sku',
        product_id: 'prod_0b661d35bf8b29a1ee',
        quantity: 1,
        discount_quantity: 1,
        initial_quantity: 1,
        amount: 64900,
        discount_amount: 64900,
        initial_amount: 64900,
        applied_discount_amount: 64900,
        price: 64900,
        subtotal_amount: 0,
        product: {
          id: 'prod_0b661d35bf8b29a1ee',
          source_id: '8196593a-7e3e-464f-95eb-ccfdc5e51a35',
          name: 'Handbag by Karl Lagerfeld',
          override: true,
        },
        sku: {
          id: 'sku_0b661d89b787ec1b6d',
          source_id: 'A0E200000001UTR',
          sku: 'Handbag by Karl Lagerfeld',
          metadata: {},
          price: 64900,
          override: true,
        },
      },
    ],
    metadata: {},
    customer_id: null,
    referrer_id: null,
    object: 'order',
  },
  tracking_id: 'track_shXeLsvg1APf2ZvqLNvsl4OEm2Bq1nFSgBLgo6FhyPCOWP+pekRtKA==',
  session: {
    key: 'ssn_XsVC4sut2l34TnKAjIHrRXahGREd6Sz2',
    type: 'LOCK',
    ttl: 7,
    ttl_unit: 'DAYS',
  },
  stacking_rules: {
    redeemables_limit: 30,
    applicable_redeemables_limit: 3,
    applicable_exclusive_redeemables_limit: 1,
    applicable_redeemables_per_category_limit: 3,
    exclusive_categories: ['cat_0e39d9b0e551edcc40'],
    joint_categories: [],
    redeemables_application_mode: 'PARTIAL',
    redeemables_sorting_rule: 'CATEGORY_HIERARCHY',
  },
};
