import { OrderPaidActions } from '../../src/commercetools/store-actions/order-paid-actions';
import {
  order,
  orderMetadataSchemaProperties,
} from './payloads/order-paid-actions-pailoads';

describe('OrderPaidActions', () => {
  it('should getCustomMetadataForOrder correctly', async () => {
    const orderPaidActions = new OrderPaidActions();
    const ctClient = {
      payments: jest.fn().mockReturnValue({
        withId: jest.fn().mockReturnValue({
          get: jest.fn().mockReturnValue({
            execute: jest
              .fn()
              .mockResolvedValue({ body: { payments: 'found', id: 123 } }),
          }),
        }),
      }),
    };
    orderPaidActions.setCtClient(ctClient as any);
    const result = await orderPaidActions.getCustomMetadataForOrder(
      order as any,
      [...orderMetadataSchemaProperties, 'payments'],
    );
    expect(result).toEqual({
      custom_filed_shippingInfo: {
        shippingMethodName: 'Standard US',
        'price.type': 'centPrecision',
        'price.currencyCode': 'USD',
        'price.centAmount': 0,
        'price.fractionDigits': 2,
        'shippingRate.price.type': 'centPrecision',
        'shippingRate.price.currencyCode': 'USD',
        'shippingRate.price.centAmount': 300,
        'shippingRate.price.fractionDigits': 2,
        'shippingRate.freeAbove.type': 'centPrecision',
        'shippingRate.freeAbove.currencyCode': 'USD',
        'shippingRate.freeAbove.centAmount': 20000,
        'shippingRate.freeAbove.fractionDigits': 2,
        'taxRate.name': '10% incl.',
        'taxRate.amount': 0.1,
        'taxRate.includedInPrice': true,
        'taxRate.country': 'US',
        'taxRate.id': '_JMEWRo5',
        'taxCategory.typeId': 'tax-category',
        'taxCategory.id': '72f8835b-53ae-4d3b-bd3b-a17dafd26c99',
        'shippingMethod.typeId': 'shipping-method',
        'shippingMethod.id': '4ec3254f-4ce4-4338-803d-1e42e6f552c6',
        'taxedPrice.totalNet.type': 'centPrecision',
        'taxedPrice.totalNet.currencyCode': 'USD',
        'taxedPrice.totalNet.centAmount': 0,
        'taxedPrice.totalNet.fractionDigits': 2,
        'taxedPrice.totalGross.type': 'centPrecision',
        'taxedPrice.totalGross.currencyCode': 'USD',
        'taxedPrice.totalGross.centAmount': 0,
        'taxedPrice.totalGross.fractionDigits': 2,
        'taxedPrice.totalTax.type': 'centPrecision',
        'taxedPrice.totalTax.currencyCode': 'USD',
        'taxedPrice.totalTax.centAmount': 0,
        'taxedPrice.totalTax.fractionDigits': 2,
        shippingMethodState: 'MatchesCart',
      },
      payments: [{ payments: 'found', id: 123 }],
      taxedPrice: {
        'totalNet.type': 'centPrecision',
        'totalNet.currencyCode': 'USD',
        'totalNet.centAmount': 33636,
        'totalNet.fractionDigits': 2,
        'totalGross.type': 'centPrecision',
        'totalGross.currencyCode': 'USD',
        'totalGross.centAmount': 37000,
        'totalGross.fractionDigits': 2,
        'taxPortions.0.rate': 0.1,
        'taxPortions.0.amount.type': 'centPrecision',
        'taxPortions.0.amount.currencyCode': 'USD',
        'taxPortions.0.amount.centAmount': 3364,
        'taxPortions.0.amount.fractionDigits': 2,
        'taxPortions.0.name': '10% incl.',
        'totalTax.type': 'centPrecision',
        'totalTax.currencyCode': 'USD',
        'totalTax.centAmount': 3364,
        'totalTax.fractionDigits': 2,
      },
      lineItems: [
        {
          id: 'd52307c5-1cc4-400b-9459-121da2d261e5',
          productId: '73ce4f06-80ad-48e6-8b36-e7102fdc8709',
          productKey: '81338',
          'name.en': 'Jeans Cycle dark blue',
          'name.de': 'Jeans Cycle dunkelblau',
          'productType.typeId': 'product-type',
          'productType.id': 'f084fa3e-01bd-4ee2-8c8a-9a18764e8841',
          'productType.version': 1,
          'productSlug.en': 'cycle-jeans-T225B0440880-darkblue',
          'productSlug.de': 'cycle-jeans-T225B0440880-dunkelblau',
          'variant.id': 1,
          'variant.sku': 'M0E20000000EE54',
          'variant.key': 'M0E20000000EE54',
          'variant.prices.0.id': 'cc49dc1d-515b-4bf7-9a49-e0da4266d9dd',
          'variant.prices.0.value.type': 'centPrecision',
          'variant.prices.0.value.currencyCode': 'EUR',
          'variant.prices.0.value.centAmount': 18500,
          'variant.prices.0.value.fractionDigits': 2,
          'variant.prices.1.id': '3d14867a-66d2-4766-a05d-b66bfd258121',
          'variant.prices.1.value.type': 'centPrecision',
          'variant.prices.1.value.currencyCode': 'EUR',
          'variant.prices.1.value.centAmount': 12131,
          'variant.prices.1.value.fractionDigits': 2,
          'variant.prices.1.customerGroup.typeId': 'customer-group',
          'variant.prices.1.customerGroup.id':
            '0c826f37-d10d-439c-bf46-ce9e17deab74',
          'variant.prices.2.id': '1728926f-e928-4eba-8aab-8338406b0f38',
          'variant.prices.2.value.type': 'centPrecision',
          'variant.prices.2.value.currencyCode': 'USD',
          'variant.prices.2.value.centAmount': 18500,
          'variant.prices.2.value.fractionDigits': 2,
          'variant.prices.2.country': 'US',
          'variant.prices.3.id': '9e7124c7-fba6-4fe3-9b13-1262a74bf054',
          'variant.prices.3.value.type': 'centPrecision',
          'variant.prices.3.value.currencyCode': 'USD',
          'variant.prices.3.value.centAmount': 12131,
          'variant.prices.3.value.fractionDigits': 2,
          'variant.prices.3.customerGroup.typeId': 'customer-group',
          'variant.prices.3.customerGroup.id':
            '0c826f37-d10d-439c-bf46-ce9e17deab74',
          'variant.prices.4.id': '268bd270-188d-480e-91ce-62f5ce36cd44',
          'variant.prices.4.value.type': 'centPrecision',
          'variant.prices.4.value.currencyCode': 'EUR',
          'variant.prices.4.value.centAmount': 14800,
          'variant.prices.4.value.fractionDigits': 2,
          'variant.prices.4.country': 'DE',
          'variant.prices.5.id': '79e2adaf-1f35-44cf-b6b6-959730676fe2',
          'variant.prices.5.value.type': 'centPrecision',
          'variant.prices.5.value.currencyCode': 'EUR',
          'variant.prices.5.value.centAmount': 14800,
          'variant.prices.5.value.fractionDigits': 2,
          'variant.prices.5.country': 'IT',
          'variant.prices.6.id': '4a76b969-9927-4499-95f3-70ba1986d792',
          'variant.prices.6.value.type': 'centPrecision',
          'variant.prices.6.value.currencyCode': 'EUR',
          'variant.prices.6.value.centAmount': 14800,
          'variant.prices.6.value.fractionDigits': 2,
          'variant.prices.6.country': 'GB',
          'variant.prices.7.id': '85475aaa-0a2a-4469-a766-1f214477c7c6',
          'variant.prices.7.value.type': 'centPrecision',
          'variant.prices.7.value.currencyCode': 'EUR',
          'variant.prices.7.value.centAmount': 16132,
          'variant.prices.7.value.fractionDigits': 2,
          'variant.prices.7.country': 'DE',
          'variant.prices.7.channel.typeId': 'channel',
          'variant.prices.7.channel.id': 'd4e8a815-830f-43bf-8506-77de565bf3f3',
          'variant.prices.8.id': 'ea15846d-304b-492c-bf9a-4f203d3ce218',
          'variant.prices.8.value.type': 'centPrecision',
          'variant.prices.8.value.currencyCode': 'EUR',
          'variant.prices.8.value.centAmount': 20165,
          'variant.prices.8.value.fractionDigits': 2,
          'variant.prices.8.channel.typeId': 'channel',
          'variant.prices.8.channel.id': '68506b79-8d88-47ab-b77d-5b54cb6eec03',
          'variant.prices.9.id': '1f7c4b96-faa9-4042-b7b7-a06cc00659dd',
          'variant.prices.9.value.type': 'centPrecision',
          'variant.prices.9.value.currencyCode': 'EUR',
          'variant.prices.9.value.centAmount': 16280,
          'variant.prices.9.value.fractionDigits': 2,
          'variant.prices.9.country': 'DE',
          'variant.prices.9.channel.typeId': 'channel',
          'variant.prices.9.channel.id': '075f15ed-e66a-49a6-8d61-786145ac1a7a',
          'variant.prices.10.id': 'e7c79b01-130c-4e3b-8b9e-0e014a18f885',
          'variant.prices.10.value.type': 'centPrecision',
          'variant.prices.10.value.currencyCode': 'EUR',
          'variant.prices.10.value.centAmount': 13468,
          'variant.prices.10.value.fractionDigits': 2,
          'variant.prices.10.country': 'DE',
          'variant.prices.10.channel.typeId': 'channel',
          'variant.prices.10.channel.id':
            'ffecbfe5-a622-4e1f-8704-ac328d94cfb5',
          'variant.prices.11.id': 'bcdbfe78-1906-445d-882e-cf4431eb84df',
          'variant.prices.11.value.type': 'centPrecision',
          'variant.prices.11.value.currencyCode': 'EUR',
          'variant.prices.11.value.centAmount': 13616,
          'variant.prices.11.value.fractionDigits': 2,
          'variant.prices.11.country': 'DE',
          'variant.prices.11.channel.typeId': 'channel',
          'variant.prices.11.channel.id':
            'c9958b11-6151-433e-83f3-4424e6fa4ac2',
          'variant.prices.12.id': '6a68bc68-3fe4-42fe-aa84-eb9efe201a23',
          'variant.prices.12.value.type': 'centPrecision',
          'variant.prices.12.value.currencyCode': 'USD',
          'variant.prices.12.value.centAmount': 16132,
          'variant.prices.12.value.fractionDigits': 2,
          'variant.prices.12.country': 'US',
          'variant.prices.12.channel.typeId': 'channel',
          'variant.prices.12.channel.id':
            '2259d32b-2c7a-4941-842a-d81fb3c878e7',
          'variant.prices.13.id': '33958888-3989-49db-b64e-124fd35aacc4',
          'variant.prices.13.value.type': 'centPrecision',
          'variant.prices.13.value.currencyCode': 'USD',
          'variant.prices.13.value.centAmount': 20165,
          'variant.prices.13.value.fractionDigits': 2,
          'variant.prices.13.channel.typeId': 'channel',
          'variant.prices.13.channel.id':
            '0399ae91-a3be-40ef-90cc-11ac36cf8a62',
          'variant.prices.14.id': '76ed4a2f-ea55-4d05-8393-1616dca4c679',
          'variant.prices.14.value.type': 'centPrecision',
          'variant.prices.14.value.currencyCode': 'USD',
          'variant.prices.14.value.centAmount': 16280,
          'variant.prices.14.value.fractionDigits': 2,
          'variant.prices.14.country': 'US',
          'variant.prices.14.channel.typeId': 'channel',
          'variant.prices.14.channel.id':
            'bcaecbbd-bf7c-4f9f-9b4b-c0cbd6240d68',
          'variant.prices.15.id': 'dae9fff7-75f0-479e-83a7-d4465b10bcdc',
          'variant.prices.15.value.type': 'centPrecision',
          'variant.prices.15.value.currencyCode': 'USD',
          'variant.prices.15.value.centAmount': 13468,
          'variant.prices.15.value.fractionDigits': 2,
          'variant.prices.15.country': 'US',
          'variant.prices.15.channel.typeId': 'channel',
          'variant.prices.15.channel.id':
            '3def0285-22e1-401c-916b-56efb977f18e',
          'variant.prices.16.id': 'b22ac8dc-c357-45d9-97d5-9d7f4aeff564',
          'variant.prices.16.value.type': 'centPrecision',
          'variant.prices.16.value.currencyCode': 'USD',
          'variant.prices.16.value.centAmount': 13616,
          'variant.prices.16.value.fractionDigits': 2,
          'variant.prices.16.country': 'US',
          'variant.prices.16.channel.typeId': 'channel',
          'variant.prices.16.channel.id':
            'db86818a-f58b-4df4-8b61-46de85d13a00',
          'variant.images.0.url':
            'https://s3-eu-west-1.amazonaws.com/commercetools-maximilian/products/081338_1_large.jpg',
          'variant.images.0.dimensions.w': 0,
          'variant.images.0.dimensions.h': 0,
          'variant.attributes.0.name': 'articleNumberManufacturer',
          'variant.attributes.0.value': 'WPT492 T225 B044 0880 001',
          'variant.attributes.1.name': 'articleNumberMax',
          'variant.attributes.1.value': '81338',
          'variant.attributes.2.name': 'matrixId',
          'variant.attributes.2.value': 'M0E20000000EE54',
          'variant.attributes.3.name': 'baseId',
          'variant.attributes.3.value': '81338',
          'variant.attributes.4.name': 'designer',
          'variant.attributes.4.value.key': 'cycle',
          'variant.attributes.4.value.label': 'Cycle',
          'variant.attributes.5.name': 'madeInItaly',
          'variant.attributes.5.value.key': 'yes',
          'variant.attributes.5.value.label': 'yes',
          'variant.attributes.6.name': 'commonSize',
          'variant.attributes.6.value.key': 'xxs',
          'variant.attributes.6.value.label': 'XXS',
          'variant.attributes.7.name': 'size',
          'variant.attributes.7.value': '24',
          'variant.attributes.8.name': 'color',
          'variant.attributes.8.value.key': 'blue',
          'variant.attributes.8.value.label.de': 'blau',
          'variant.attributes.8.value.label.it': 'blu',
          'variant.attributes.8.value.label.en': 'blue',
          'variant.attributes.9.name': 'colorFreeDefinition',
          'variant.attributes.9.value.en': 'dark blue',
          'variant.attributes.9.value.de': 'dunkelblau',
          'variant.attributes.10.name': 'style',
          'variant.attributes.10.value.key': 'sporty',
          'variant.attributes.10.value.label': 'sporty',
          'variant.attributes.11.name': 'gender',
          'variant.attributes.11.value.key': 'women',
          'variant.attributes.11.value.label': 'Damen',
          'variant.attributes.12.name': 'season',
          'variant.attributes.12.value': 's15',
          'price.id': '1728926f-e928-4eba-8aab-8338406b0f38',
          'price.value.type': 'centPrecision',
          'price.value.currencyCode': 'USD',
          'price.value.centAmount': 18500,
          'price.value.fractionDigits': 2,
          'price.country': 'US',
          quantity: 1,
          'taxRate.name': '10% incl.',
          'taxRate.amount': 0.1,
          'taxRate.includedInPrice': true,
          'taxRate.country': 'US',
          'taxRate.id': '_JMEWRo5',
          addedAt: '2023-06-14T11:48:15.511Z',
          lastModifiedAt: '2023-06-14T11:48:15.511Z',
          'state.0.quantity': 1,
          'state.0.state.typeId': 'state',
          'state.0.state.id': 'ad3930da-ae5c-4c7e-8ae0-2dfb99d52f50',
          priceMode: 'Platform',
          lineItemMode: 'Standard',
          'totalPrice.type': 'centPrecision',
          'totalPrice.currencyCode': 'USD',
          'totalPrice.centAmount': 18500,
          'totalPrice.fractionDigits': 2,
          'taxedPrice.totalNet.type': 'centPrecision',
          'taxedPrice.totalNet.currencyCode': 'USD',
          'taxedPrice.totalNet.centAmount': 16818,
          'taxedPrice.totalNet.fractionDigits': 2,
          'taxedPrice.totalGross.type': 'centPrecision',
          'taxedPrice.totalGross.currencyCode': 'USD',
          'taxedPrice.totalGross.centAmount': 18500,
          'taxedPrice.totalGross.fractionDigits': 2,
          'taxedPrice.totalTax.type': 'centPrecision',
          'taxedPrice.totalTax.currencyCode': 'USD',
          'taxedPrice.totalTax.centAmount': 1682,
          'taxedPrice.totalTax.fractionDigits': 2,
          'custom.type.typeId': 'type',
          'custom.type.id': '69840f60-bd39-4958-b3fc-85bf6c492791',
        },
        {
          id: '9d0b608c-f02d-43c2-8417-dcecb43ecc88',
          productId: '73ce4f06-80ad-48e6-8b36-e7102fdc8709',
          productKey: '81338',
          'name.en': 'Jeans Cycle dark blue',
          'name.de': 'Jeans Cycle dunkelblau',
          'productType.typeId': 'product-type',
          'productType.id': 'f084fa3e-01bd-4ee2-8c8a-9a18764e8841',
          'productType.version': 1,
          'productSlug.en': 'cycle-jeans-T225B0440880-darkblue',
          'productSlug.de': 'cycle-jeans-T225B0440880-dunkelblau',
          'variant.id': 1,
          'variant.sku': 'M0E20000000EE54',
          'variant.key': 'M0E20000000EE54',
          'variant.prices.0.id': 'cc49dc1d-515b-4bf7-9a49-e0da4266d9dd',
          'variant.prices.0.value.type': 'centPrecision',
          'variant.prices.0.value.currencyCode': 'EUR',
          'variant.prices.0.value.centAmount': 18500,
          'variant.prices.0.value.fractionDigits': 2,
          'variant.prices.1.id': '3d14867a-66d2-4766-a05d-b66bfd258121',
          'variant.prices.1.value.type': 'centPrecision',
          'variant.prices.1.value.currencyCode': 'EUR',
          'variant.prices.1.value.centAmount': 12131,
          'variant.prices.1.value.fractionDigits': 2,
          'variant.prices.1.customerGroup.typeId': 'customer-group',
          'variant.prices.1.customerGroup.id':
            '0c826f37-d10d-439c-bf46-ce9e17deab74',
          'variant.prices.2.id': '1728926f-e928-4eba-8aab-8338406b0f38',
          'variant.prices.2.value.type': 'centPrecision',
          'variant.prices.2.value.currencyCode': 'USD',
          'variant.prices.2.value.centAmount': 18500,
          'variant.prices.2.value.fractionDigits': 2,
          'variant.prices.2.country': 'US',
          'variant.prices.3.id': '9e7124c7-fba6-4fe3-9b13-1262a74bf054',
          'variant.prices.3.value.type': 'centPrecision',
          'variant.prices.3.value.currencyCode': 'USD',
          'variant.prices.3.value.centAmount': 12131,
          'variant.prices.3.value.fractionDigits': 2,
          'variant.prices.3.customerGroup.typeId': 'customer-group',
          'variant.prices.3.customerGroup.id':
            '0c826f37-d10d-439c-bf46-ce9e17deab74',
          'variant.prices.4.id': '268bd270-188d-480e-91ce-62f5ce36cd44',
          'variant.prices.4.value.type': 'centPrecision',
          'variant.prices.4.value.currencyCode': 'EUR',
          'variant.prices.4.value.centAmount': 14800,
          'variant.prices.4.value.fractionDigits': 2,
          'variant.prices.4.country': 'DE',
          'variant.prices.5.id': '79e2adaf-1f35-44cf-b6b6-959730676fe2',
          'variant.prices.5.value.type': 'centPrecision',
          'variant.prices.5.value.currencyCode': 'EUR',
          'variant.prices.5.value.centAmount': 14800,
          'variant.prices.5.value.fractionDigits': 2,
          'variant.prices.5.country': 'IT',
          'variant.prices.6.id': '4a76b969-9927-4499-95f3-70ba1986d792',
          'variant.prices.6.value.type': 'centPrecision',
          'variant.prices.6.value.currencyCode': 'EUR',
          'variant.prices.6.value.centAmount': 14800,
          'variant.prices.6.value.fractionDigits': 2,
          'variant.prices.6.country': 'GB',
          'variant.prices.7.id': '85475aaa-0a2a-4469-a766-1f214477c7c6',
          'variant.prices.7.value.type': 'centPrecision',
          'variant.prices.7.value.currencyCode': 'EUR',
          'variant.prices.7.value.centAmount': 16132,
          'variant.prices.7.value.fractionDigits': 2,
          'variant.prices.7.country': 'DE',
          'variant.prices.7.channel.typeId': 'channel',
          'variant.prices.7.channel.id': 'd4e8a815-830f-43bf-8506-77de565bf3f3',
          'variant.prices.8.id': 'ea15846d-304b-492c-bf9a-4f203d3ce218',
          'variant.prices.8.value.type': 'centPrecision',
          'variant.prices.8.value.currencyCode': 'EUR',
          'variant.prices.8.value.centAmount': 20165,
          'variant.prices.8.value.fractionDigits': 2,
          'variant.prices.8.channel.typeId': 'channel',
          'variant.prices.8.channel.id': '68506b79-8d88-47ab-b77d-5b54cb6eec03',
          'variant.prices.9.id': '1f7c4b96-faa9-4042-b7b7-a06cc00659dd',
          'variant.prices.9.value.type': 'centPrecision',
          'variant.prices.9.value.currencyCode': 'EUR',
          'variant.prices.9.value.centAmount': 16280,
          'variant.prices.9.value.fractionDigits': 2,
          'variant.prices.9.country': 'DE',
          'variant.prices.9.channel.typeId': 'channel',
          'variant.prices.9.channel.id': '075f15ed-e66a-49a6-8d61-786145ac1a7a',
          'variant.prices.10.id': 'e7c79b01-130c-4e3b-8b9e-0e014a18f885',
          'variant.prices.10.value.type': 'centPrecision',
          'variant.prices.10.value.currencyCode': 'EUR',
          'variant.prices.10.value.centAmount': 13468,
          'variant.prices.10.value.fractionDigits': 2,
          'variant.prices.10.country': 'DE',
          'variant.prices.10.channel.typeId': 'channel',
          'variant.prices.10.channel.id':
            'ffecbfe5-a622-4e1f-8704-ac328d94cfb5',
          'variant.prices.11.id': 'bcdbfe78-1906-445d-882e-cf4431eb84df',
          'variant.prices.11.value.type': 'centPrecision',
          'variant.prices.11.value.currencyCode': 'EUR',
          'variant.prices.11.value.centAmount': 13616,
          'variant.prices.11.value.fractionDigits': 2,
          'variant.prices.11.country': 'DE',
          'variant.prices.11.channel.typeId': 'channel',
          'variant.prices.11.channel.id':
            'c9958b11-6151-433e-83f3-4424e6fa4ac2',
          'variant.prices.12.id': '6a68bc68-3fe4-42fe-aa84-eb9efe201a23',
          'variant.prices.12.value.type': 'centPrecision',
          'variant.prices.12.value.currencyCode': 'USD',
          'variant.prices.12.value.centAmount': 16132,
          'variant.prices.12.value.fractionDigits': 2,
          'variant.prices.12.country': 'US',
          'variant.prices.12.channel.typeId': 'channel',
          'variant.prices.12.channel.id':
            '2259d32b-2c7a-4941-842a-d81fb3c878e7',
          'variant.prices.13.id': '33958888-3989-49db-b64e-124fd35aacc4',
          'variant.prices.13.value.type': 'centPrecision',
          'variant.prices.13.value.currencyCode': 'USD',
          'variant.prices.13.value.centAmount': 20165,
          'variant.prices.13.value.fractionDigits': 2,
          'variant.prices.13.channel.typeId': 'channel',
          'variant.prices.13.channel.id':
            '0399ae91-a3be-40ef-90cc-11ac36cf8a62',
          'variant.prices.14.id': '76ed4a2f-ea55-4d05-8393-1616dca4c679',
          'variant.prices.14.value.type': 'centPrecision',
          'variant.prices.14.value.currencyCode': 'USD',
          'variant.prices.14.value.centAmount': 16280,
          'variant.prices.14.value.fractionDigits': 2,
          'variant.prices.14.country': 'US',
          'variant.prices.14.channel.typeId': 'channel',
          'variant.prices.14.channel.id':
            'bcaecbbd-bf7c-4f9f-9b4b-c0cbd6240d68',
          'variant.prices.15.id': 'dae9fff7-75f0-479e-83a7-d4465b10bcdc',
          'variant.prices.15.value.type': 'centPrecision',
          'variant.prices.15.value.currencyCode': 'USD',
          'variant.prices.15.value.centAmount': 13468,
          'variant.prices.15.value.fractionDigits': 2,
          'variant.prices.15.country': 'US',
          'variant.prices.15.channel.typeId': 'channel',
          'variant.prices.15.channel.id':
            '3def0285-22e1-401c-916b-56efb977f18e',
          'variant.prices.16.id': 'b22ac8dc-c357-45d9-97d5-9d7f4aeff564',
          'variant.prices.16.value.type': 'centPrecision',
          'variant.prices.16.value.currencyCode': 'USD',
          'variant.prices.16.value.centAmount': 13616,
          'variant.prices.16.value.fractionDigits': 2,
          'variant.prices.16.country': 'US',
          'variant.prices.16.channel.typeId': 'channel',
          'variant.prices.16.channel.id':
            'db86818a-f58b-4df4-8b61-46de85d13a00',
          'variant.images.0.url':
            'https://s3-eu-west-1.amazonaws.com/commercetools-maximilian/products/081338_1_large.jpg',
          'variant.images.0.dimensions.w': 0,
          'variant.images.0.dimensions.h': 0,
          'variant.attributes.0.name': 'articleNumberManufacturer',
          'variant.attributes.0.value': 'WPT492 T225 B044 0880 001',
          'variant.attributes.1.name': 'articleNumberMax',
          'variant.attributes.1.value': '81338',
          'variant.attributes.2.name': 'matrixId',
          'variant.attributes.2.value': 'M0E20000000EE54',
          'variant.attributes.3.name': 'baseId',
          'variant.attributes.3.value': '81338',
          'variant.attributes.4.name': 'designer',
          'variant.attributes.4.value.key': 'cycle',
          'variant.attributes.4.value.label': 'Cycle',
          'variant.attributes.5.name': 'madeInItaly',
          'variant.attributes.5.value.key': 'yes',
          'variant.attributes.5.value.label': 'yes',
          'variant.attributes.6.name': 'commonSize',
          'variant.attributes.6.value.key': 'xxs',
          'variant.attributes.6.value.label': 'XXS',
          'variant.attributes.7.name': 'size',
          'variant.attributes.7.value': '24',
          'variant.attributes.8.name': 'color',
          'variant.attributes.8.value.key': 'blue',
          'variant.attributes.8.value.label.de': 'blau',
          'variant.attributes.8.value.label.it': 'blu',
          'variant.attributes.8.value.label.en': 'blue',
          'variant.attributes.9.name': 'colorFreeDefinition',
          'variant.attributes.9.value.en': 'dark blue',
          'variant.attributes.9.value.de': 'dunkelblau',
          'variant.attributes.10.name': 'style',
          'variant.attributes.10.value.key': 'sporty',
          'variant.attributes.10.value.label': 'sporty',
          'variant.attributes.11.name': 'gender',
          'variant.attributes.11.value.key': 'women',
          'variant.attributes.11.value.label': 'Damen',
          'variant.attributes.12.name': 'season',
          'variant.attributes.12.value': 's15',
          'price.id': '1728926f-e928-4eba-8aab-8338406b0f38',
          'price.value.type': 'centPrecision',
          'price.value.currencyCode': 'USD',
          'price.value.centAmount': 18500,
          'price.value.fractionDigits': 2,
          'price.country': 'US',
          quantity: 1,
          'taxRate.name': '10% incl.',
          'taxRate.amount': 0.1,
          'taxRate.includedInPrice': true,
          'taxRate.country': 'US',
          'taxRate.id': '_JMEWRo5',
          addedAt: '2023-06-15T08:20:31.622Z',
          lastModifiedAt: '2023-06-15T08:20:31.622Z',
          'state.0.quantity': 1,
          'state.0.state.typeId': 'state',
          'state.0.state.id': 'ad3930da-ae5c-4c7e-8ae0-2dfb99d52f50',
          priceMode: 'Platform',
          lineItemMode: 'Standard',
          'totalPrice.type': 'centPrecision',
          'totalPrice.currencyCode': 'USD',
          'totalPrice.centAmount': 18500,
          'totalPrice.fractionDigits': 2,
          'taxedPrice.totalNet.type': 'centPrecision',
          'taxedPrice.totalNet.currencyCode': 'USD',
          'taxedPrice.totalNet.centAmount': 16818,
          'taxedPrice.totalNet.fractionDigits': 2,
          'taxedPrice.totalGross.type': 'centPrecision',
          'taxedPrice.totalGross.currencyCode': 'USD',
          'taxedPrice.totalGross.centAmount': 18500,
          'taxedPrice.totalGross.fractionDigits': 2,
          'taxedPrice.totalTax.type': 'centPrecision',
          'taxedPrice.totalTax.currencyCode': 'USD',
          'taxedPrice.totalTax.centAmount': 1682,
          'taxedPrice.totalTax.fractionDigits': 2,
          'custom.type.typeId': 'type',
          'custom.type.id': '69840f60-bd39-4958-b3fc-85bf6c492791',
        },
      ],
    });
  });
});
