import { Order } from '@commercetools/platform-sdk';

export const orderPaidWithCustomCodesResponse = {
  type: 'Order',
  id: 'd805726e-5a6b-46b2-9d8d-f7aeb00c0f25',
  version: 3,
  versionModifiedAt: '2024-06-20T11:15:09.095Z',
  lastMessageSequenceNumber: 3,
  createdAt: '2024-06-20T11:14:50.755Z',
  lastModifiedAt: '2024-06-20T11:15:09.095Z',
  lastModifiedBy: {
    isPlatformClient: true,
    user: { typeId: 'user', id: 'e617a5c4-f5a7-441f-b049-b88b5f652e5f' },
  },
  createdBy: {
    clientId: 'xk5XhnOY0sEnvWZaI6cELzDE',
    isPlatformClient: false,
    anonymousId: '1ff6d7b2-a1a1-4f63-a63b-2d80ab5b0797',
  },
  anonymousId: '1ff6d7b2-a1a1-4f63-a63b-2d80ab5b0797',
  totalPrice: {
    type: 'centPrecision',
    currencyCode: 'EUR',
    centAmount: 16800,
    fractionDigits: 2,
  },
  taxedPrice: {
    totalNet: {
      type: 'centPrecision',
      currencyCode: 'EUR',
      centAmount: 12521,
      fractionDigits: 2,
    },
    totalGross: {
      type: 'centPrecision',
      currencyCode: 'EUR',
      centAmount: 16800,
      fractionDigits: 2,
    },
    taxPortions: [],
    totalTax: {
      type: 'centPrecision',
      currencyCode: 'EUR',
      centAmount: 4279,
      fractionDigits: 2,
    },
  },
  country: 'DE',
  taxedShippingPrice: {
    totalNet: {
      type: 'centPrecision',
      currencyCode: 'EUR',
      centAmount: 252,
      fractionDigits: 2,
    },
    totalGross: {
      type: 'centPrecision',
      currencyCode: 'EUR',
      centAmount: 300,
      fractionDigits: 2,
    },
    taxPortions: [],
    totalTax: {
      type: 'centPrecision',
      currencyCode: 'EUR',
      centAmount: 48,
      fractionDigits: 2,
    },
  },
  orderState: 'Confirmed',
  paymentState: 'Paid',
  syncInfo: [],
  returnInfo: [],
  taxMode: 'Platform',
  inventoryMode: 'None',
  taxRoundingMode: 'HalfEven',
  taxCalculationMode: 'LineItemLevel',
  origin: 'Customer',
  shippingMode: 'Single',
  shippingInfo: {
    shippingMethodName: 'Standard EU',
    price: {
      type: 'centPrecision',
      currencyCode: 'EUR',
      centAmount: 300,
      fractionDigits: 2,
    },
    shippingRate: {
      price: {
        type: 'centPrecision',
        currencyCode: 'EUR',
        centAmount: 300,
        fractionDigits: 2,
      },
      freeAbove: {
        type: 'centPrecision',
        currencyCode: 'EUR',
        centAmount: 20000,
        fractionDigits: 2,
      },
      tiers: [],
    },
    taxRate: {
      name: '19% incl.',
      amount: 0.19,
      includedInPrice: true,
      country: 'DE',
      id: '8QjXEInm',
      subRates: [],
    },
    taxCategory: {
      typeId: 'tax-category',
      id: '3bb32e63-f609-4eeb-9400-95f80ef6cc76',
    },
    deliveries: [],
    shippingMethod: {
      typeId: 'shipping-method',
      id: '58188fc9-fa9c-47d8-883c-75a0ea5492b9',
    },
    taxedPrice: {
      totalNet: {
        type: 'centPrecision',
        currencyCode: 'EUR',
        centAmount: 252,
        fractionDigits: 2,
      },
      totalGross: {
        type: 'centPrecision',
        currencyCode: 'EUR',
        centAmount: 300,
        fractionDigits: 2,
      },
      taxPortions: [],
      totalTax: {
        type: 'centPrecision',
        currencyCode: 'EUR',
        centAmount: 48,
        fractionDigits: 2,
      },
    },
    shippingMethodState: 'MatchesCart',
  },
  shippingAddress: {
    firstName: 'tyy',
    lastName: 'tyy',
    streetName: 'adsasd',
    postalCode: '123',
    city: 'ads',
    country: 'DE',
    email: '22@o2.pl',
  },
  shipping: [],
  lineItems: [
    {
      id: '13c3a702-4f16-47a5-93cc-1770ad08cec4',
      productId: '2a0a5b55-2b9c-4572-8074-bbcefdacf390',
      productKey: '78893',
      name: { en: 'Pants Jacob Cohen green', de: 'Hose Jacob Cohen grün' },
      productType: {
        typeId: 'product-type',
        id: '9730a637-875e-4810-93aa-a8e56cffabe1',
        version: 1,
      },
      productSlug: {
        en: 'jacob-cohen-trousers-j622-697-green',
        de: 'jacob-cohen-hose-j622-697-gruen',
      },
      variant: {
        id: 1,
        sku: 'M0E20000000DUIR',
        key: 'M0E20000000DUIR',
        prices: [
          { id: 'df3d1ce2-f29c-426f-9dcd-516bcda6de49', value: [Object] },
          {
            id: '2724701f-10ca-4df6-a202-b15c8069b2d3',
            value: [Object],
            customerGroup: [Object],
          },
          {
            id: '9bff832b-3beb-4d12-b172-888b8291f592',
            value: [Object],
            country: 'US',
          },
          {
            id: 'cd2bab21-ec4d-41cc-bc59-4320f000f51a',
            value: [Object],
            customerGroup: [Object],
          },
          {
            id: '04431c6f-4492-4af4-ae1b-a4d625fb5d46',
            value: [Object],
            country: 'DE',
          },
          {
            id: 'f07b6fca-988e-494b-a2cd-12d69c7e44ff',
            value: [Object],
            country: 'IT',
          },
          {
            id: '28951fef-9595-46a9-8abc-2764b99d0ebf',
            value: [Object],
            country: 'GB',
          },
          {
            id: '9eeb4ff4-367c-4868-b994-f5691d8d3d15',
            value: [Object],
            country: 'DE',
            channel: [Object],
          },
          {
            id: '0230a70a-5e67-4806-9398-9b7487f3e7da',
            value: [Object],
            channel: [Object],
          },
          {
            id: '3380ee50-7db3-4a37-a5ec-507db1121208',
            value: [Object],
            country: 'DE',
            channel: [Object],
          },
          {
            id: '8ddb3a98-7f21-4c4e-9693-cad5d15cf8af',
            value: [Object],
            country: 'DE',
            channel: [Object],
          },
          {
            id: 'd8a1a64e-d0af-4430-8f47-a4efa7e3cbe7',
            value: [Object],
            country: 'DE',
            channel: [Object],
          },
          {
            id: '01b5655d-f509-4cd9-9860-bbc65aad708f',
            value: [Object],
            country: 'US',
            channel: [Object],
          },
          {
            id: '2cc19517-fb23-4966-8af9-ee7fc5f15a82',
            value: [Object],
            channel: [Object],
          },
          {
            id: '08214e59-0996-4ecc-ace2-3da554737407',
            value: [Object],
            country: 'US',
            channel: [Object],
          },
          {
            id: 'ee140832-7f85-4886-87fc-735d3aeb9a01',
            value: [Object],
            country: 'US',
            channel: [Object],
          },
          {
            id: '984c72a6-e25f-4d13-9189-3a50be3a6192',
            value: [Object],
            country: 'US',
            channel: [Object],
          },
        ],
        images: [
          {
            url: 'https://s3-eu-west-1.amazonaws.com/commercetools-maximilian/products/078893_1_large.jpg',
            dimensions: [Object],
          },
        ],
        attributes: [
          {
            name: 'articleNumberManufacturer',
            value: 'J622 COM VIN 8605 697 697',
          },
          { name: 'articleNumberMax', value: '78893' },
          { name: 'matrixId', value: 'M0E20000000DUIR' },
          { name: 'baseId', value: '78893' },
          { name: 'designer', value: [Object] },
          { name: 'madeInItaly', value: [Object] },
          { name: 'commonSize', value: [Object] },
          { name: 'size', value: '24' },
          { name: 'color', value: [Object] },
          { name: 'colorFreeDefinition', value: [Object] },
          { name: 'style', value: [Object] },
          { name: 'gender', value: [Object] },
          { name: 'season', value: 's15' },
        ],
        assets: [],
      },
      price: {
        id: '04431c6f-4492-4af4-ae1b-a4d625fb5d46',
        value: {
          type: 'centPrecision',
          currencyCode: 'EUR',
          centAmount: 26500,
          fractionDigits: 2,
        },
        country: 'DE',
      },
      quantity: 1,
      discountedPricePerQuantity: [],
      taxRate: {
        name: '19% incl.',
        amount: 0.19,
        includedInPrice: true,
        country: 'DE',
        id: '8QjXEInm',
        subRates: [],
      },
      addedAt: '2024-06-20T11:14:03.503Z',
      lastModifiedAt: '2024-06-20T11:14:03.503Z',
      state: [],
      priceMode: 'Platform',
      lineItemMode: 'Standard',
      totalPrice: {
        type: 'centPrecision',
        currencyCode: 'EUR',
        centAmount: 26500,
        fractionDigits: 2,
      },
      taxedPrice: {
        totalNet: {
          type: 'centPrecision',
          currencyCode: 'EUR',
          centAmount: 22269,
          fractionDigits: 2,
        },
        totalGross: {
          type: 'centPrecision',
          currencyCode: 'EUR',
          centAmount: 26500,
          fractionDigits: 2,
        },
        taxPortions: [{ rate: 0.19, amount: [Object], name: '19% incl.' }],
        totalTax: {
          type: 'centPrecision',
          currencyCode: 'EUR',
          centAmount: 4231,
          fractionDigits: 2,
        },
      },
      custom: {
        type: { typeId: 'type', id: '83213f56-58cb-4dd2-8ff3-0fb45c04cb10' },
        fields: {},
      },
    },
  ],
  customLineItems: [
    {
      id: '162e8d87-7bf1-4880-9a38-408e362c95ea',
      name: { en: 'Coupon codes discount', de: 'Gutscheincodes rabatt' },
      money: {
        type: 'centPrecision',
        currencyCode: 'EUR',
        centAmount: -10000,
        fractionDigits: 2,
      },
      slug: 'Voucher, ',
      quantity: 1,
      discountedPricePerQuantity: [],
      taxCategory: {
        typeId: 'tax-category',
        id: 'c9cac365-9d19-4bd9-bfc3-3e06f57e58ad',
      },
      taxRate: {
        name: 'coupon',
        amount: 0,
        includedInPrice: true,
        country: 'DE',
        id: 'zQwpoV17',
        subRates: [],
      },
      state: [
        {
          quantity: 1,
          state: {
            typeId: 'state',
            id: '960f9f2f-a798-49dd-afd5-7cc89a4f3ff6',
          },
        },
      ],
      totalPrice: {
        type: 'centPrecision',
        currencyCode: 'EUR',
        centAmount: -10000,
        fractionDigits: 2,
      },
      taxedPrice: {
        totalNet: {
          type: 'centPrecision',
          currencyCode: 'EUR',
          centAmount: -10000,
          fractionDigits: 2,
        },
        totalGross: {
          type: 'centPrecision',
          currencyCode: 'EUR',
          centAmount: -10000,
          fractionDigits: 2,
        },
        totalTax: {
          type: 'centPrecision',
          currencyCode: 'EUR',
          centAmount: 0,
          fractionDigits: 2,
        },
      },
    },
  ],
  transactionFee: true,
  discountCodes: [],
  directDiscounts: [],
  cart: { typeId: 'cart', id: '815d8b92-a4c9-49de-8d06-50e54a45a0cf' },
  custom: {
    type: { typeId: 'type', id: 'f19c3900-a6d5-4f73-9f12-4e09d2cfd792' },
    fields: {
      couponsLimit: 5,
      discount_codes: [
        '{"status":"AVAILABLE","value":2000,"code":"promo_IWXEwkEdivlYa8a5qKzNqXxN","type":"promotion_tier"}',
        '{"status":"AVAILABLE","value":1000,"code":"promo_0ONBGj3HnpivcjhrwZZt4zTG","type":"promotion_tier"}',
        '{"code":"WXCQRBDKTP","status":"APPLIED","type":"voucher","value":10000}',
      ],
      shippingProductSourceIds: [],
      session: 'ssn_WtM5V9yjHpmtHMOpYrlyqozHGRaO1zNy',
    },
  },
  billingAddress: {
    firstName: 'tyy',
    lastName: 'tyy',
    streetName: 'adsasd',
    postalCode: '123',
    city: 'ads',
    country: 'DE',
    email: '22@o2.pl',
  },
  itemShippingAddresses: [],
  refusedGifts: [],
} as unknown as Order;
